sources:
  - name: sentry
    handler:
      graphql:
        endpoint: https://api.goldsky.com/api/public/project_cmh50tw8e0001sqp25vrrff4t/subgraphs/sentry/2.0.1/gn
    transforms:
      - autoPagination:
          # You might want to disable schema validation for faster startup
          validateSchema: true
