sources:
  - name: sentry
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/f37507ea64fb/xai/sentry-sepolia/api
    transforms:
      - autoPagination:
          # You might want to disable schema validation for faster startup
          validateSchema: true