specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Referee
    network: arbitrum-sepolia
    source:
      address: "0xF84D76755a68bE9DFdab9a0b6d934896Ceab957b"
      abi: Referee
      startBlock: 26974804
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Challenge
        - Submission
        - SentryWallet
      abis:
        - name: Referee
          file: ./abis/Referee.json
      eventHandlers:
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: AssertionSubmitted(indexed uint256,indexed uint256)
          handler: handleAssertionSubmitted
        - event: ChallengeClosed(indexed uint256)
          handler: handleChallengeClosed
        - event: ChallengeExpired(indexed uint256)
          handler: handleChallengeExpired
        - event: ChallengeSubmitted(indexed uint256)
          handler: handleChallengeSubmitted
        - event: RewardsClaimed(indexed uint256,uint256)
          handler: handleRewardsClaimed
        - event: BatchRewardsClaimed(indexed uint256,uint256,uint256)
          handler: handleBatchRewardsClaimed
        - event: Approval(indexed address,indexed address,bool)
          handler: handleApproval
        - event: KycStatusChanged(indexed address,bool)
          handler: handleKycStatusChanged
        - event: StakedV1(indexed address,uint256,uint256)
          handler: handleStakedV1
        - event: UnstakeV1(indexed address,uint256,uint256)
          handler: handleUnstakeV1
        - event: NewPoolSubmission(indexed uint256,indexed address,uint256,uint256)
          handler: handleNewPoolSubmission
        - event: UpdatePoolSubmission(indexed uint256,indexed address,uint256,uint256,uint256,uint256)
          handler: handleUpdatePoolSubmission
        - event: PoolRewardsClaimed(indexed uint256,indexed address,uint256,uint256)
          handler: handlePoolRewardsClaimed

        - event: AssertionSubmittedV2(indexed uint256,indexed uint256,bytes,bool)
          handler: handleAssertionSubmittedV2
        - event: RewardsClaimedV2(indexed uint256,indexed uint256,uint256)
          handler: handleRewardsClaimedV2
        - event: AssertionCancelled(indexed uint256,indexed uint256)
          handler: handleAssertionCancelled

      file: ./src/referee.ts
  - kind: ethereum
    name: NodeLicense
    network: arbitrum-sepolia
    source:
      address: "0x07C05C6459B0F86A6aBB3DB71C259595d22af3C2"
      abi: NodeLicense
      startBlock: 15609970
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - SentryKey
      abis:
        - name: NodeLicense
          file: ./abis/NodeLicense.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./src/node-license.ts
  - kind: ethereum
    name: PoolFactory
    network: arbitrum-sepolia
    source:
      address: "0x87Ae2373007C01FBCED0dCCe4a23CA3f17D1fA9A"
      abi: PoolFactory
      startBlock: 26975569
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - PoolInfo
      abis:
        - name: PoolFactory
          file: ./abis/PoolFactory.json
        - name: TinyKeysAirdrop
          file: ./abis/TinyKeysAirdrop.json
      eventHandlers:
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: StakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleStakeKeys
        - event: UnstakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstakeKeys
        - event: PoolCreated(indexed uint256,indexed address,indexed address,uint256)
          handler: handlePoolCreated
        - event: UpdatePoolDelegate(indexed address,indexed address)
          handler: handleUpdatePoolDelegate
        - event: StakeEsXai(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleStakeEsXai
        - event: UnstakeEsXai(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstakeEsXai
        - event: UpdateMetadata(indexed address)
          handler: handleUpdateMetadata
        - event: UnstakeRequestStarted(indexed address,indexed address,indexed uint256,uint256,bool)
          handler: handleUnstakeRequest
        - event: UpdateShares(indexed address)
          handler: handleUpdatePendingShares
        - event: ClaimFromPool(indexed address,indexed address)
          handler: handleClaimFromPool
        - event: UpdateDelayPeriods()
          handler: handleUpdateDelayPeriods
      file: ./src/pool-factory.ts
  - kind: ethereum
    name: Xai
    network: arbitrum-sepolia
    source:
      address: "0x724E98F16aC707130664bb00F4397406F74732D0"
      abi: Xai
      startBlock: 26975569
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - ConvertedToEsXaiEvent
      abis:
        - name: Xai
          file: ./abis/Xai.json
      eventHandlers:
        - event: ConvertedToEsXai(indexed address,uint256)
          handler: handleConvertedToEsXai
      file: ./src/xai.ts
  - kind: ethereum
    name: TinyKeysAirdrop
    network: arbitrum-sepolia
    source:
      address: "0xA65E7524b4714d1BB3208aEd9e9fC666806148a5"
      abi: TinyKeysAirdrop
      startBlock: 62587483
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - AirdropSegmentCompleteEvent
      abis:
        - name: TinyKeysAirdrop
          file: ./abis/TinyKeysAirdrop.json
      eventHandlers:
        - event: AirdropSegmentComplete(uint256,uint256)
          handler: handleAirdropSegmentComplete
      file: ./src/tiny-keys-airdrop.ts