specVersion: 1.0.0
indexerHints:
  prune: auto
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Referee
    network: arbitrum-sepolia
    source:
      address: "0x58B5083d042b122606565315EabE13acd006e934"
      abi: Referee
      startBlock: 106164427
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Challenge
        - Submission
        - SentryWallet
      abis:
        - name: Referee
          file: ./abis/Referee.json
      eventHandlers:
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: AssertionSubmitted(indexed uint256,indexed uint256)
          handler: handleAssertionSubmitted
        - event: ChallengeClosed(indexed uint256)
          handler: handleChallengeClosed
        - event: ChallengeExpired(indexed uint256)
          handler: handleChallengeExpired
        - event: ChallengeSubmitted(indexed uint256)
          handler: handleChallengeSubmitted
        - event: RewardsClaimed(indexed uint256,uint256)
          handler: handleRewardsClaimed
        - event: BatchRewardsClaimed(indexed uint256,uint256,uint256)
          handler: handleBatchRewardsClaimed
        - event: Approval(indexed address,indexed address,bool)
          handler: handleApproval
        - event: KycStatusChanged(indexed address,bool)
          handler: handleKycStatusChanged
        - event: StakedV1(indexed address,uint256,uint256)
          handler: handleStakedV1
        - event: UnstakeV1(indexed address,uint256,uint256)
          handler: handleUnstakeV1
        - event: NewBulkSubmission(indexed uint256,indexed address,uint256,uint256)
          handler: handleNewBulkSubmission
        - event: UpdateBulkSubmission(indexed uint256,indexed address,uint256,uint256,uint256,uint256)
          handler: handleUpdateBulkSubmission
        - event: BulkRewardsClaimed(indexed uint256,indexed address,uint256,uint256)
          handler: handleBulkRewardsClaimed

      file: ./src/referee.ts
  - kind: ethereum
    name: NodeLicense
    network: arbitrum-sepolia
    source:
      address: "0x4B8E2935779305D1976D2855315D521d05027322"
      abi: NodeLicense
      startBlock: 106164427
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - SentryKey
      abis:
        - name: NodeLicense
          file: ./abis/NodeLicense.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,indexed uint256)
          handler: handleTransfer
      file: ./src/node-license.ts
  - kind: ethereum
    name: PoolFactory
    network: arbitrum-sepolia
    source:
      address: "0xfCeCe5D7ba423C7730591fF7a2239581Cdc39eC1"
      abi: PoolFactory
      startBlock: 106164427
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - PoolInfo
      abis:
        - name: PoolFactory
          file: ./abis/PoolFactory.json
      eventHandlers:
        - event: Initialized(uint8)
          handler: handleInitialized
        - event: StakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleStakeKeys
        - event: UnstakeKeys(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstakeKeys
        - event: PoolCreated(indexed uint256,indexed address,indexed address,uint256)
          handler: handlePoolCreated
        - event: UpdatePoolDelegate(indexed address,indexed address)
          handler: handleUpdatePoolDelegate
        - event: StakeEsXai(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleStakeEsXai
        - event: UnstakeEsXai(indexed address,indexed address,uint256,uint256,uint256)
          handler: handleUnstakeEsXai
        - event: UpdateMetadata(indexed address)
          handler: handleUpdateMetadata
        - event: UnstakeRequestStarted(indexed address,indexed address,indexed uint256,uint256,bool)
          handler: handleUnstakeRequest
        - event: UpdateShares(indexed address)
          handler: handleUpdatePendingShares
        - event: ClaimFromPool(indexed address,indexed address)
          handler: handleClaimFromPool
        - event: UpdateDelayPeriods()
          handler: handleUpdateDelayPeriods
        - event: StakeKeysV2(indexed address,indexed address,uint256,uint256,uint256,uint256[])
          handler: handleStakeKeysV2
        - event: UnstakeKeysV2(indexed address,indexed address,uint256,uint256,uint256,uint256,uint256[])
          handler: handleUnstakeKeysV2
        - event: PoolCreatedV2(indexed uint256,indexed address,indexed address,uint256,address,uint256[],uint32[3],string[3],string[])
          handler: handlePoolCreatedV2
        - event: UnstakeEsXaiV2(indexed address,indexed address,uint256,uint256,uint256,uint256)
          handler: handleUnstakeEsXaiV2
        - event: UpdateMetadataV2(indexed address,string[3],string[])
          handler: handleUpdateMetadataV2
        - event: UpdateSharesV2(indexed address,uint32[3])
          handler: handleUpdatePendingSharesV2
      file: ./src/pool-factory.ts
  - kind: ethereum
    name: Xai
    network: arbitrum-sepolia
    source:
      address: "0x85fD733B0903D135Bc50F1B41B7ad5fF14377ada"
      abi: Xai
      startBlock: 106164427
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - ConvertedToEsXaiEvent
      abis:
        - name: Xai
          file: ./abis/Xai.json
      eventHandlers:
        - event: ConvertedToEsXai(indexed address,uint256)
          handler: handleConvertedToEsXai
      file: ./src/xai.ts
  - kind: ethereum
    name: Rollup
    network: arbitrum-sepolia
    source:
      address: "0x855049Ea1999b2cB2eA820031c17a8f99700b9E0"
      abi: Rollup
      startBlock: 106164427
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - NodeConfirmation
      abis:
        - name: Rollup
          file: ./abis/Rollup.json
      eventHandlers:
        - event: NodeConfirmed(indexed uint64,bytes32,bytes32)
          handler: handleNodeConfirmed
      file: ./src/referee.ts