name: Deploy Web Connect

on:
  workflow_dispatch:
    inputs:
      cloudflare_project:
        description: 'Cloudflare project to deploy to'
        required: true
        type: choice
        options:
          - sentry
          - sentry-develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build monorepo for development
        if: ${{ github.event.inputs.cloudflare_project == 'sentry-develop' }}
        run: npx nx run @sentry/web-connect:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }
          VITE_APP_ENV: development

      - name: Build monorepo for production
        if: ${{ github.event.inputs.cloudflare_project == 'sentry' }}
        run: npx nx run @sentry/web-connect:build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }

      - name: Deploy to Cloudflare Pages
        run: |
          rm apps/web-connect/dist/xai-drop-permits.JSON 
          npx wrangler pages deploy dist --project-name=${{ github.event.inputs.cloudflare_project }} --branch=main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

        # Popular action to deploy to GitHub Pages:
        # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./apps/web-connect/dist
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com