name: PR deploy

on:
  pull_request:
    types: [review_requested]
    branches:
      - "*"

  pull_request_review:
    types: [submitted]
    branches:
        - '*'

jobs:
  build:
    if: github.event_name == 'pull_request' || github.event.review.state == 'approved'
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the PR branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up environment variables for container names
      - name: Set container names
        run: |
          echo "WEB_CONNECT_CONTAINER_NAME=web-connect-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "WEB_STAKING_CONTAINER_NAME=web-staking-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          
      # Step 3: Build web-connect and web-staking services using docker compose
      - name: Build Docker services
        run: |
          docker compose -f .dev-deploy/docker-compose.yml build

      - name: Check if containers exist and remove them
        run: |
          # Check if the web-connect container exists, and remove it if it does
          if [ "$(docker ps -a -q -f name=${{ env.WEB_CONNECT_CONTAINER_NAME }})" ]; then
            docker stop ${{ env.WEB_CONNECT_CONTAINER_NAME }} || true
            docker rm ${{ env.WEB_CONNECT_CONTAINER_NAME }} || true
          fi

          # Check if the web-staking container exists, and remove it if it does
          if [ "$(docker ps -a -q -f name=${{ env.WEB_STAKING_CONTAINER_NAME }})" ]; then
            docker stop ${{ env.WEB_STAKING_CONTAINER_NAME }} || true
            docker rm ${{ env.WEB_STAKING_CONTAINER_NAME }} || true
          fi

      - name: Run web-connect container
        run: |
          docker compose -f .dev-deploy/docker-compose.yml run -d --name ${{ env.WEB_CONNECT_CONTAINER_NAME }} web-connect

      - name: Run web-staking container
        run: |
          docker compose -f .dev-deploy/docker-compose.yml run -d --name ${{ env.WEB_STAKING_CONTAINER_NAME }} \
            -e NEXT_PUBLIC_APP_ENV=development \
            -e MONGODB_URL=${{ secrets.MONGODB_URL }} \
            web-staking
