name: Web Staking - Semantic Release and Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # Inline install of semantic-release packages
      - name: Install semantic-release and plugins
        run: |
          pnpm add -D -w semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/git @semantic-release/github @semantic-release/changelog 

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: get_version
        with:
          dry_run: false
          tag_format: "${version}-web-staking"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
